# Generated by Django 5.2.7 on 2025-10-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('video', 'Video'), ('course', 'Course'), ('article', 'Article')], default='video', max_length=20)),
                ('platform', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('started', 'Started'), ('in-progress', 'In Progress'), ('completed', 'Completed')], default='started', max_length=20)),
                ('hours_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('difficulty_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3)),
                ('notes', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('data', 'Data'), ('devops', 'DevOps'), ('other', 'Other')], default='other', max_length=20)),
                ('recommended_resources', models.TextField(blank=True, default='{}')),
                ('mastery_prediction', models.TextField(blank=True, default='{}')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('total_learning_days', models.IntegerField(default=0)),
                ('streak_started_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
